version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: synapse-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: synapse
      MONGO_INITDB_ROOT_PASSWORD: synapse123
    volumes:
      - mongodb_data:/data/db
    networks:
      - synapse-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: synapse-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - synapse-network

  # Face Recognition Service
  face-recognition:
    build:
      context: ./src/backend/face_recognition_service
      dockerfile: Dockerfile
    container_name: synapse-face-recognition
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - redis
    networks:
      - synapse-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # WAHA WhatsApp Service
  waha:
    image: devlikeapro/waha:latest
    container_name: synapse-waha
    restart: unless-stopped
    ports:
      - "3001:3000"  # WAHA runs on port 3000 internally
    environment:
      # WAHA Configuration
      - WHATSAPP_SESSIONS_FOLDER=/app/sessions
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WHATSAPP_API_KEY=${WAHA_API_KEY:-your-secure-api-key-here}
      - WHATSAPP_FILES_LIFETIME=0  # Disable automatic file cleanup
      - WHATSAPP_RESTART_ALL_SESSIONS=true
      - WHATSAPP_START_SESSION=default
      # Performance settings
      - WHATSAPP_MAX_ATTACHMENT_SIZE=50
      - WHATSAPP_DOWNLOAD_MEDIA=false  # Disable automatic media download to improve performance
    volumes:
      - waha_sessions:/app/sessions
      - waha_media:/app/media
    networks:
      - synapse-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Backend Service (for development)
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: synapse-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://synapse:synapse123@mongodb:27017/synapse?authSource=admin
      - REDIS_URL=redis://redis:6379
      - FACE_RECOGNITION_SERVICE_URL=http://face-recognition:5001
      - JWT_SECRET=your-jwt-secret-here
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=http://localhost:5173
      # WAHA Configuration
      - WAHA_SERVICE_URL=http://waha:3000
      - WAHA_API_KEY=${WAHA_API_KEY:-your-secure-api-key-here}
    volumes:
      - ./src/backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
      - face-recognition
      - waha
    networks:
      - synapse-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  waha_sessions:
    driver: local
  waha_media:
    driver: local

networks:
  synapse-network:
    driver: bridge