version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: synapse-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: synapse
      MONGO_INITDB_ROOT_PASSWORD: synapse123
    volumes:
      - mongodb_data:/data/db
    networks:
      - synapse-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: synapse-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - synapse-network

  # Face Recognition Service
  face-recognition:
    build:
      context: ./src/backend/face_recognition_service
      dockerfile: Dockerfile
    container_name: synapse-face-recognition
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - redis
    networks:
      - synapse-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Backend Service (for development)
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: synapse-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://synapse:synapse123@mongodb:27017/synapse?authSource=admin
      - REDIS_URL=redis://redis:6379
      - FACE_RECOGNITION_SERVICE_URL=http://face-recognition:5001
      - JWT_SECRET=your-jwt-secret-here
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./src/backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
      - face-recognition
    networks:
      - synapse-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  synapse-network:
    driver: bridge