#!/bin/bash
# Agents Dashboard Fix Script
# Auto-generated by diagnostic tool

echo "🚀 FIXING AGENTS DASHBOARD ISSUES..."

# 1. Install dependencies if missing
echo "📦 Installing dependencies..."
cd src/frontend && npm install --silent
cd ../backend && npm install --silent
cd ../..

# 2. Start MongoDB if not running
echo "🗄️  Starting MongoDB..."
if ! pgrep mongod > /dev/null; then
  if command -v brew > /dev/null; then
    brew services start mongodb/brew/mongodb-community
  elif command -v systemctl > /dev/null; then
    sudo systemctl start mongod
  else
    echo "⚠️  Please start MongoDB manually"
  fi
fi

# 3. Build frontend if needed
echo "🏗️  Building frontend..."
cd src/frontend && npm run build --silent
cd ../..

# 4. Start backend server
echo "🔄 Starting backend server..."
cd src/backend && npm run dev &
BACKEND_PID=$!
cd ../..

# 5. Start frontend server  
echo "🔄 Starting frontend server..."
cd src/frontend && npm run dev &
FRONTEND_PID=$!
cd ../..

echo "✅ Dashboard should be available at:"
echo "   Frontend: http://localhost:3000"
echo "   Backend:  http://localhost:3001"
echo ""
echo "Press Ctrl+C to stop servers"

# Wait for Ctrl+C
trap "kill $BACKEND_PID $FRONTEND_PID; exit" INT
wait
