services:
  - type: web
    name: synapse-frontend
    runtime: static
    buildCommand: cd src/frontend && npm install --legacy-peer-deps && npm run build
    staticPublishPath: src/frontend/dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_BACKEND_ROOT_URL
        value: https://synapse-backend-7lq6.onrender.com
      - key: VITE_API_BASE_URL
        value: https://synapse-backend-7lq6.onrender.com/api/v1

  - type: web
    name: synapse-backend
    env: docker
    dockerfilePath: ./src/backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TWITTER_BEARER_TOKEN
        value: AAAAAAAAAAAAAAAAAAAAAMC1nwEAAAAARjSmFvESyJicKzC4XJGIBA5uHJU%3DhFQAsucL0p9gW32XHZXGXokNJZXXuw3D86QrVlf4m2Hr1ViheD
      - key: NEWS_API_KEY
        sync: false
      - key: TRANSCRIPTION_SERVICE_URL
        value: https://synapse-transcription.onrender.com
      - key: FRONTEND_URL
        value: https://synapse-frontend.onrender.com
      - key: BACKEND_URL
        value: https://synapse-backend-7lq6.onrender.com
      - key: CREWAI_SERVICE_URL
        value: https://synapse-crewai.onrender.com
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"
      - key: EMBEDDING_PROVIDER
        value: voyage
      - key: VOYAGE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: synapse-docs
      - key: WAHA_SERVICE_URL
        value: https://synapse-waha.onrender.com
      - key: WAHA_API_KEY
        value: waha-synapse-2025-secure
      # Search and Vector Database Configuration
      - key: CHROMA_URL
        value: http://localhost:8000
      - key: SEARCH_FALLBACK_MODE
        value: "true"

  - type: web
    name: synapse-waha
    runtime: docker
    dockerImage: devlikeapro/waha:latest
    healthCheckPath: /api/sessions
    startupTimeout: 600
    envVars:
      - key: PORT
        value: 3000
      - key: WAHA_API_KEY
        value: waha-synapse-2025-secure
      - key: WAHA_AUTO_START_DELAY_SECONDS
        value: "10"
      - key: WAHA_DASHBOARD_PASSWORD
        sync: false
      - key: WAHA_DASHBOARD_USERNAME
        value: admin
      - key: WAHA_LOG_FORMAT
        value: JSON
      - key: WAHA_LOG_LEVEL
        value: info
      - key: WAHA_PRINT_QR
        value: "false"
      - key: WAHA_WORKER_RESTART_SESSIONS
        value: "true"
      - key: WHATSAPP_API_HOSTNAME
        value: 0.0.0.0
      - key: WHATSAPP_API_PORT
        value: 3000
      - key: WHATSAPP_RESTART_ALL_SESSIONS
        value: "true"
      - key: WHATSAPP_SESSIONS_MONGO_URL
        sync: false
      - key: WHATSAPP_HOOK_URL
        value: https://synapse-backend-7lq6.onrender.com/api/v1/waha/webhook
      - key: WHATSAPP_HOOK_EVENTS
        value: "session.status,message"

  - type: web
    name: synapse-crewai
    runtime: python
    buildCommand: cd src/backend/services/crewai-agents && pip install --upgrade pip && pip install -r requirements.txt && ls -la
    startCommand: cd src/backend/services/crewai-agents && ls -la && python main_enhanced.py
    plan: starter
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        value: SynapseAgent/1.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: PORT
        value: 5000
      - key: ENVIRONMENT
        value: production
