services:
  - type: web
    name: synapse-frontend
    runtime: static
    buildCommand: cd src/frontend && npm install && npm run build
    staticPublishPath: src/frontend/dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_BACKEND_ROOT_URL
        value: https://synapse-pxad.onrender.com
      - key: VITE_API_BASE_URL
        value: https://synapse-pxad.onrender.com/api/v1

  - type: web
    name: synapse-backend
    env: docker
    dockerfilePath: ./src/backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TWITTER_BEARER_TOKEN
        value: AAAAAAAAAAAAAAAAAAAAAMC1nwEAAAAARjSmFvESyJicKzC4XJGIBA5uHJU%3DhFQAsucL0p9gW32XHZXGXokNJZXXuw3D86QrVlf4m2Hr1ViheD
      - key: NEWS_API_KEY
        sync: false
      - key: TRANSCRIPTION_SERVICE_URL
        value: https://synapse-transcription.onrender.com
      - key: FRONTEND_URL
        value: https://synapse-frontend.onrender.com
      - key: CREWAI_SERVICE_URL
        value: https://synapse-crewai.onrender.com
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 

  - type: web
    name: synapse-crewai
    runtime: python
    buildCommand: cd src/backend/services/crewai-agents && pip install --upgrade pip && pip install -r requirements.txt && ls -la
    startCommand: cd src/backend/services/crewai-agents && ls -la && python main_enhanced.py
    plan: starter
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        value: SynapseAgent/1.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: PORT
        value: 5000
      - key: ENVIRONMENT
        value: production
