services:
  - type: web
    name: synapse-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable" 