services:
  - type: web
    name: synapse-crewai
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "chmod +x start.sh && ./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PORT
        value: "10000"
      - key: FLASK_APP
        value: "main.py"
      - key: FLASK_ENV
        value: "production"
      - key: LOG_LEVEL
        value: "INFO"
      # AI APIs (set in Render dashboard)
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      # Social Media APIs (optional - set in Render dashboard)
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        value: "SynapseAgent/1.0"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      # Other services
      - key: PERPLEXITY_API_KEY
        sync: false 