const express = require('express');
const cors = require('cors');
const app = express();

app.use(cors());
app.use(express.json());

// Sample news data with rich CrewAI analysis
const newsData = [
  {
    _id: 'analysis-1',
    userId: 'demo-user',
    title: '🤖 AI Market Analysis: Multi-Agent Research Report',
    description: 'Comprehensive analysis by CrewAI agents on latest AI market trends',
    content: `## Executive Summary

Our multi-agent system has analyzed over 500 sources to bring you this comprehensive market report.

### Key Findings:
- **Market Growth**: AI market experiencing 47% YoY growth, reaching $450B valuation
- **Enterprise Adoption**: 73% of Fortune 500 companies now using AI in production
- **Investment Surge**: Q4 2024 saw record $52B in AI investments globally
- **Talent Demand**: 2.3 million AI job openings worldwide, 89% increase from 2023

## Trending Topics Analysis

### 🔥 Hot Topics (Last 7 Days)

- **GPT-5 Launch** - 342 mentions across platforms - Sentiment: 92% positive
- **AI Regulation** - 289 mentions - Sentiment: Mixed (45% positive, 35% neutral, 20% negative)
- **Multimodal AI** - 256 mentions - Sentiment: 87% positive
- **Edge Computing** - 198 mentions - Sentiment: 78% positive
- **AI Ethics** - 176 mentions - Sentiment: 65% positive

## Source Analysis

### 📰 News Articles (152 analyzed)
- OpenAI announces GPT-5 with revolutionary reasoning capabilities
- Google DeepMind achieves new breakthrough in protein structure prediction
- Microsoft integrates advanced AI across entire product suite
- Amazon launches AI-powered logistics optimization saving $2B annually

### 🔴 Reddit Insights (89 threads analyzed)
- r/MachineLearning: "New training method reduces compute by 10x" (2.3k upvotes)
- r/artificial: "Is AGI possible by 2030?" heated debate (1.8k comments)
- r/singularity: Analysis of consciousness in large language models
- r/LocalLLaMA: Open-source models catching up to proprietary ones

### 💼 LinkedIn Professional Updates (67 posts)
- CEO insights: "AI transformed our operations, 35% cost reduction"
- Industry report: Healthcare AI adoption up 156% in 2024
- Expert panel: The future of AI in financial services
- Case study: Small business success with AI automation

### 📱 Telegram Channels (43 channels monitored)
- Breaking: New open-source model beats GPT-4 on benchmarks
- Alert: Major AI company acquisition for $5.2B
- Update: China announces $100B AI infrastructure investment

## AI-Generated Insights

\`\`\`json
{
  "market_sentiment": "bullish",
  "confidence_score": 0.89,
  "growth_projection": "47% CAGR through 2027",
  "key_sectors": {
    "healthcare": { "growth": "156%", "investment": "$18B" },
    "finance": { "growth": "98%", "investment": "$24B" },
    "retail": { "growth": "67%", "investment": "$11B" },
    "manufacturing": { "growth": "89%", "investment": "$15B" }
  },
  "emerging_trends": [
    "Multimodal AI becoming standard",
    "Edge AI for real-time processing",
    "AI agents for autonomous operations",
    "Quantum-AI hybrid systems"
  ],
  "risk_factors": [
    "Regulatory uncertainty in major markets",
    "Talent shortage creating bottlenecks",
    "Ethical concerns slowing adoption",
    "Infrastructure costs for smaller companies"
  ]
}
\`\`\`

## Strategic Recommendations

1. **Immediate Actions**
   - Accelerate AI talent acquisition and training programs
   - Establish AI governance and ethics frameworks
   - Begin pilot programs in high-ROI areas

2. **Short-term (3-6 months)**
   - Develop strategic partnerships with AI providers
   - Implement AI-powered automation in key processes
   - Create data infrastructure for AI readiness

3. **Long-term (6-12 months)**
   - Build proprietary AI capabilities
   - Explore emerging AI technologies
   - Prepare for regulatory compliance

## Conclusion

The AI revolution is accelerating faster than predicted. Organizations that act now will have significant competitive advantages. Our agent network will continue monitoring these trends 24/7.

---
*Report generated by CrewAI Multi-Agent System v2.0*
*Agents involved: Market Analyst, Reddit Scraper, News Aggregator, LinkedIn Monitor, Telegram Watcher*
*Analysis timestamp: ${new Date().toISOString()}*`,
    url: '#internal-analysis',
    urlToImage: 'https://picsum.photos/600/400?random=analysis',
    source: { id: 'crewai_analysis', name: 'CrewAI Multi-Agent System' },
    author: 'AI Agent Collective',
    publishedAt: new Date().toISOString(),
    category: 'AI Analysis',
    tags: ['crewai', 'analysis', 'ai', 'market-research', 'multi-agent'],
    sentiment: 'positive',
    relevanceScore: 0.98,
    status: 'summarized',
    isRead: false,
    isFavorite: true,
    runId: 'run-123',
    metadata: {
      sourceUrls: [
        'https://openai.com/blog/gpt-5',
        'https://deepmind.google/research',
        'https://reddit.com/r/MachineLearning',
        'https://linkedin.com/pulse/ai-transformation'
      ],
      agentCount: 5,
      sourcesAnalyzed: 500,
      confidence: 0.89
    }
  },
  {
    _id: 'news-2',
    userId: 'demo-user',
    title: 'Breaking: GPT-5 Revolutionizes AI Landscape',
    description: 'OpenAI\'s latest model shows unprecedented capabilities',
    summary: 'GPT-5 demonstrates human-level reasoning, multimodal understanding, and reduced hallucinations.',
    content: 'Full analysis of GPT-5 capabilities and impact on the industry...',
    url: 'https://example.com/gpt5-launch',
    urlToImage: 'https://picsum.photos/400/300?random=gpt5',
    source: { id: 'tech_news', name: 'TechCrunch' },
    author: 'Sarah Chen',
    publishedAt: new Date(Date.now() - 2*3600000).toISOString(),
    category: 'AI Technology',
    tags: ['gpt5', 'openai', 'breakthrough'],
    sentiment: 'positive',
    relevanceScore: 0.96,
    isRead: false,
    isFavorite: false
  },
  {
    _id: 'reddit-3',
    userId: 'demo-user',
    title: '🔴 Reddit: "Is AGI Actually Possible by 2030?"',
    description: 'Heated debate on r/singularity with experts weighing in',
    content: 'Community discussion on AGI timelines with various expert opinions...',
    url: 'https://reddit.com/r/singularity/agi-2030',
    source: { id: 'reddit', name: 'r/singularity' },
    author: 'u/future_researcher',
    publishedAt: new Date(Date.now() - 5*3600000).toISOString(),
    category: 'Discussion',
    tags: ['reddit', 'agi', 'debate', 'singularity'],
    sentiment: 'neutral',
    relevanceScore: 0.78,
    isRead: true,
    readAt: new Date(Date.now() - 3600000).toISOString(),
    isFavorite: false
  },
  {
    _id: 'linkedin-4',
    userId: 'demo-user',
    title: '💼 LinkedIn: AI Reduces Enterprise Costs by 35%',
    description: 'Fortune 500 CEO shares transformation journey',
    content: 'Detailed case study on AI implementation in enterprise...',
    url: 'https://linkedin.com/pulse/ai-transformation',
    source: { id: 'linkedin', name: 'LinkedIn' },
    author: 'Michael Roberts, CEO',
    publishedAt: new Date(Date.now() - 8*3600000).toISOString(),
    category: 'Business',
    tags: ['linkedin', 'enterprise', 'case-study', 'roi'],
    sentiment: 'positive',
    relevanceScore: 0.85,
    isRead: false,
    isFavorite: false
  },
  {
    _id: 'telegram-5',
    userId: 'demo-user',
    title: '📱 Telegram: Open-Source Model Beats GPT-4',
    description: 'Breaking news from AI research channels',
    content: 'New open-source model shows impressive benchmark results...',
    url: '#telegram-ai-news',
    source: { id: 'telegram', name: 'AI Research Channel' },
    author: '@ai_research',
    publishedAt: new Date(Date.now() - 10*3600000).toISOString(),
    category: 'Research',
    tags: ['telegram', 'open-source', 'breakthrough'],
    sentiment: 'positive',
    relevanceScore: 0.82,
    isRead: false,
    isFavorite: false
  },
  {
    _id: 'news-6',
    userId: 'demo-user',
    title: 'Healthcare AI Saves Millions of Lives',
    description: 'New diagnostic system achieves 99% accuracy for rare diseases',
    content: 'Revolutionary healthcare AI system details...',
    url: 'https://example.com/healthcare-ai',
    urlToImage: 'https://picsum.photos/400/300?random=health',
    source: { id: 'medical_news', name: 'Medical Today' },
    author: 'Dr. Emily Watson',
    publishedAt: new Date(Date.now() - 24*3600000).toISOString(),
    category: 'Healthcare',
    tags: ['healthcare', 'ai', 'medical', 'breakthrough'],
    sentiment: 'positive',
    relevanceScore: 0.91,
    isRead: false,
    isFavorite: true
  }
];

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({ status: 'ok', message: 'Mock backend is running' });
});

// Get news items
app.get('/api/news', (req, res) => {
  const source = req.query.source;
  const runId = req.query.runId;
  
  let filteredData = [...newsData];
  
  if (source) {
    filteredData = filteredData.filter(item => item.source.id === source);
  }
  
  if (runId) {
    filteredData = filteredData.filter(item => item.runId === runId);
  }
  
  res.json({
    success: true,
    data: filteredData,
    pagination: {
      currentPage: 1,
      totalPages: 1,
      totalItems: filteredData.length,
      itemsPerPage: 20,
      hasNextPage: false,
      hasPrevPage: false
    }
  });
});

// Get categories
app.get('/api/news/categories', (req, res) => {
  const categories = [...new Set(newsData.map(item => item.category).filter(Boolean))];
  res.json({ success: true, data: categories });
});

// Get statistics
app.get('/api/news/statistics', (req, res) => {
  res.json({
    success: true,
    data: {
      totalItems: newsData.length,
      unreadItems: newsData.filter(item => !item.isRead).length,
      favoriteItems: newsData.filter(item => item.isFavorite).length,
      archivedItems: 0,
      last24Hours: 4,
      last7Days: newsData.length,
      readPercentage: Math.round((newsData.filter(item => item.isRead).length / newsData.length) * 100)
    }
  });
});

// Mark as read
app.post('/api/news/:id/read', (req, res) => {
  const item = newsData.find(n => n._id === req.params.id);
  if (item) {
    item.isRead = true;
    item.readAt = new Date().toISOString();
  }
  res.json({ success: true, data: item });
});

// Toggle favorite
app.post('/api/news/:id/favorite', (req, res) => {
  const item = newsData.find(n => n._id === req.params.id);
  if (item) {
    item.isFavorite = !item.isFavorite;
  }
  res.json({ success: true, data: item });
});

// Archive
app.post('/api/news/:id/archive', (req, res) => {
  const item = newsData.find(n => n._id === req.params.id);
  if (item) {
    item.status = req.body.archive ? 'archived' : 'pending';
  }
  res.json({ success: true, data: item });
});

// Delete
app.delete('/api/news/:id', (req, res) => {
  const index = newsData.findIndex(n => n._id === req.params.id);
  if (index > -1) {
    newsData.splice(index, 1);
  }
  res.json({ success: true, message: 'Deleted successfully' });
});

// Mock authentication
app.post('/api/auth/login', (req, res) => {
  res.json({
    success: true,
    data: {
      user: { 
        id: 'demo-user', 
        email: 'demo@synapse.ai', 
        name: 'Demo User' 
      },
      token: 'demo-jwt-token-123'
    }
  });
});

app.get('/api/auth/me', (req, res) => {
  res.json({
    success: true,
    data: { 
      id: 'demo-user', 
      email: 'demo@synapse.ai', 
      name: 'Demo User' 
    }
  });
});

// Start server
const PORT = process.env.PORT || 3001;
app.listen(PORT, () => {
  console.log(`✅ Mock backend running on port ${PORT}`);
  console.log(`📍 Health check: http://localhost:${PORT}/health`);
  console.log(`📰 News API: http://localhost:${PORT}/api/news`);
});